services:
  backend:
    stop_signal: SIGTERM
    stop_grace_period: 20s
    build:
      context: backend
      dockerfile: Dockerfile
    
    ports:
      - 8000:8000
    
    volumes:
      - ./imdb_dataset:/app/imdb_dataset
      - ./data:/app/data
  
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
