networks:
  app_network:
    driver: bridge

services:
  backend:
    container_name: backend
    stop_signal: SIGTERM
    stop_grace_period: 20s
    build:
      context: backend
      dockerfile: Dockerfile
    networks:
      - app_network
    
    ports:
      - 8000:8000
    
    volumes:
      - ./imdb_dataset:/app/imdb_dataset
      - ./data:/app/data
  
  frontend:
    container_name: frontend
    build: 
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - app_network
